This is a big one. Make ubuntu.img its maximum size to hopefully fit any system.img we can come up with. Make the Android image conversion more resilient by making the correct size location for the sparse file. Clean up /data/recovery correctly and sync it when we're done. Add a few || true statements to prevent crashing for stupid reasons. And remove a >/dev/null so that we get all of the errors.

diff --git a/rootstock-touch-install b/rootstock-touch-install
--- a/rootstock-touch-install
+++ b/rootstock-touch-install
@@ -41,14 +41,16 @@ do_shell()
 convert_android_img()
 {
 	if file $SYSIMG | grep -v ": Linux rev 1.0 ext4" >/dev/null; then
+	    echo "Converting sparse image to contiguious image"
 		simg2img $SYSIMG $WORKDIR/system.img.raw
-        echo -n "Converting from sparse ext4 image to mountable ext4 image... "
-        simg2img $SYSIMG tmp.img >/dev/null
-        resize2fs -M tmp.img >/dev/null 2>&1
-        mv tmp.img $SYSIMG
-        echo "[Done]"
+		mkdir $TMPMOUNT
+		mount -t ext4 -o loop $WORKDIR/system.img.raw $TMPMOUNT
+		IMAGE_SIZE=`wc -c < $SYSIMG`
+		make_ext4fs -l $IMAGE_SIZE $WORKDIR/system.img $TMPMOUNT
+		SYSIMAGE=$WORKDIR/system.img
+	else
+		SYSIMAGE=$SYSIMG
 	fi
-	SYSIMAGE=$SYSIMG
 }
 
 send_busybox() {
@@ -76,10 +78,10 @@ prepare_ubuntu_system()
 		echo -n "keep option set, keeping user data ... "
 	fi
 
-	do_shell "dd if=/dev/zero of=/data/ubuntu.img seek=600K bs=4096 count=0 >/dev/null 2>&1"
-	do_shell "mkfs.ext2 -F /data/ubuntu.img >/dev/null 2>&1"
+	do_shell "dd if=/dev/zero of=/data/ubuntu.img seek=511K bs=4096 count=0 2>&1"
+	do_shell "mkfs.ext2 -F /data/ubuntu.img 2>&1"
 	do_shell "mkdir -p /data/recovery/system"
-	do_shell "mount -o loop /data/ubuntu.img /data/recovery/system/"
+	do_shell "mount -t ext4 -o loop /data/ubuntu.img /data/recovery/system/"
 
 	# system.img is the deprecated name, but we make link to ubuntu.img
 	do_shell "ln /data/ubuntu.img /data/system.img"
@@ -97,11 +99,13 @@ cleanup()
 cleanup_device()
 {
 	[ -e $WORKDIR/device-clean ] && return
-	do_shell "umount /data/recovery/system/ 2>/dev/null && rm -rf /data/recovery/system 2>/dev/null"
+	do_shell "umount /data/recovery/system/ && rm -rf /data/recovery/system 2>/dev/null"
 	do_shell "rm -f /data/$TARBALL"
 	if [ ! -z "$BUSYBOX_PUSH" ]; then
 		do_shell "rm $BUSYBOX 2>/dev/null"
 	fi
+	do_shell "rm -rf /data/recovery >/dev/null 2>&1"
+	do_shell "sync"
 	[ -e $WORKDIR ] && touch $WORKDIR/device-clean 2>/dev/null || true
 }
 
@@ -203,7 +207,7 @@ if [ ! -z "$BUSYBOX_PUSH" ]; then
 fi
 
 echo -n "transfering rootfs tarball ... "
-adb push $TARPATH /data/ >/dev/null 2>&1
+adb push $TARPATH /data/ 2>&1
 echo "[done]"
 
 if [ ! -z "$CUST_TARPATH" ]; then
@@ -224,11 +228,12 @@ do_shell "mkdir -p /data/recovery/system/android/persist"
 do_shell "mkdir -p /data/recovery/system/userdata"
 do_shell "[ -e /data/recovery/system/SWAP.swap ] && mv /data/recovery/system/SWAP.swap /data/SWAP.img || exit 0"
 for link in cache data factory firmware persist system; do
-	do_shell "cd /data/recovery/system && ln -s /android/$link $link"
-done
+    # We really don't care if this fails, so || true it is!
+	do_shell "cd /data/recovery/system && ln -s /android/$link $link" || true
+done || true
 do_shell "cd /data/recovery/system/lib && ln -s /system/lib/modules modules"
 do_shell "cd /data/recovery/system && ln -s /android/system/vendor vendor"
-do_shell "[ -e /data/recovery/system/etc/mtab ] && rm /data/recovery/system/etc/mtab || exit 0"
+do_shell "[ -e /data/recovery/system/etc/mtab ] && rm /data/recovery/system/etc/mtab || true"
 do_shell "cd /data/recovery/system/etc && ln -s /proc/mounts mtab"
 if [ ! -z "$WIPE_PATH" ]; then
 	do_shell "echo ' ' >/data/recovery/system/$WIPE_PATH || true"
@@ -245,7 +250,7 @@ fi
 echo -n "adding android system image to installation ... "
 convert_android_img
 ANDROID_DIR="/data/recovery/system/var/lib/lxc/android/"
-adb push $SYSIMAGE $ANDROID_DIR >/dev/null 2>&1
+adb push $SYSIMAGE $ANDROID_DIR 2>&1
 echo "[done]"
 
 echo -n "enabling Mir ... "
@@ -257,4 +262,4 @@ cleanup_device
 echo "[done]"
 
 echo "rebooting device"
-adb reboot
+#adb reboot
